### ISSUE TITLE
[BUG]Hi i am trying to training the model but the final results I get 2 index files, no pth files. 

### ISSUE THREAD

**Issue by thomaskarado** [IAHispano/Applio#293]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Assets**
If applicable, add screenshots/videos to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]

**Additional context**

**Comment by blaise-tk** [comment]
![image](https://github.com/IAHispano/Applio/assets/133521603/9b7f35c5-c95b-4ef9-83df-ef85ea605d36)
We need info

**Comment by blaise-tk** [comment]
Fixed.

**Comment by brcisna** [comment]
I am still getting this on Debian Linux, Python=3.10.12
two index files are generated no .pth file

Thank You,
